services:
  prometheus:
    volumes:
      - ./local/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  coroot-graft:
    build:
      context: ../..
      dockerfile: build/Dockerfile
      args:
        BERING_REPOSITORY: ${BERING_REPOSITORY:-https://github.com/MB3R-Lab/Bering}
        BERING_REF: ${BERING_REF:-812b69982293a02b1be46ee2b2161beced2f658a}
        SHEAFT_REPOSITORY: ${SHEAFT_REPOSITORY:-https://github.com/MB3R-Lab/Sheaft}
        SHEAFT_REF: ${SHEAFT_REF:-7a37c5908a721157f9178d6173395f1cbb29d493}
        VERSION: ${APP_VERSION:-0.1.1}
    image: coroot-graft-local:dev
    restart: always
    command: ["serve", "-config", "/etc/coroot-graft/graft.yaml"]
    environment:
      COROOT_GRAFT_COROOT_PASSWORD: ${COROOT_GRAFT_COROOT_PASSWORD:-secret}
      COROOT_GRAFT_WEBHOOK_SECRET: ${COROOT_GRAFT_WEBHOOK_SECRET:-local-secret}
    depends_on:
      - coroot
    volumes:
      - ./local/graft.yaml:/etc/coroot-graft/graft.yaml:ro
      - ./local/analysis.default.yaml:/etc/coroot-graft/analysis.default.yaml:ro
      - coroot_graft_data:/var/lib/coroot-graft
    ports:
      - "8095:8095"

volumes:
  coroot_graft_data: {}
